development:
  secret_key_base: 9ac2d0ad8ebcc312090e99d745006d3cf8
  meetup_api_key: 123 # see Readme
  rollbar_access_token: 123

test:
  secret_key_base: a1580ad61ccb6ac60f9f256948cf63d6e20

# production environment is provided by configuration managment
