# you will have to add a file .env holding your meetup api key
development:
  secret_key_base: 9ac2d0ad8ebcc312090e99d745006d3cf8
  meetup_api_key: <%= ENV['MEETUP_API_KEY'] %>
  rollbar_access_token: 123

test:
  secret_key_base: a1580ad61ccb6ac60f9f256948cf63d6e20

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  meetup_api_key: <%= ENV['MEETUP_API_KEY'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
